language: python
sudo: false

env:
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install busted
  - luarocks install luacov
  - luarocks install luacov-coveralls
  
script:
  - busted -Xhelper travis,$LUA -t blackbox --verbose

after_success:
  - luacov-coveralls -c $TRAVIS_BUILD_DIR/new_test/luacov.config --exclude $TRAVIS_BUILD_DIR/new_test/
  - $PWD/lua_install/bin/luacov -c $TRAVIS_BUILD_DIR/new_test/luacov.config
  - grep "Summary" -B1 -A1000 $TRAVIS_BUILD_DIR/new_test/luacov.report.out

notifications:
  email:
    on_success: change
    on_failure: change