language: python
sudo: false

env:
  - LUA="lua=5.2"

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install busted

script:
  - busted -Xhelper travis,$LUA -t blackbox --verbose

notifications:
  email:
    on_success: change
    on_failure: change