name: luarocks
base: core18
version: git
summary: LuaRocks is the package manager for the Lua programming language. # 79 char long summary
description: |
  It allows you to install Lua modules as self-contained packages called rocks, which also contain version dependency information.
  This information can be used both during installation, so that when one rock is requested all rocks it depends on are installed as well, and also optionally at run time, so that when a module is required, the correct version is loaded.
  LuaRocks supports both local and remote repositories, and multiple local rocks trees.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # should be replaced with 'strict'

parts:
  luarocks:
    plugin: make
    source: .
    build-packages:  
      - build-essential
      - libreadline-dev
    stage-packages:
      - lua5.3
      - liblua5.3-dev
      - unzip
    override-build: |
      ./configure
      make build
      snapcraftctl build

apps:
  luarocks:
    command: usr/local/bin/luarocks
  luarocks-admin:
    command: usr/local/bin/luarocks-admin
